name: env
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - libgdal
  - gdal<3.6.2
  - proj
  - rasterio>=1.3.2
  - libpq
  - git
  - wget
  - unzip
  - htop
  - tmux
  - vim
  - rio-cogeo
  - aiobotocore
  - awscli
  - boto3
  - affine
  - aiohttp
  - aioitertools
  - aiosignal
  - astropy
  - async-timeout
  - attrs
  - Babel
  - blinker
  - boltons
  - Bottleneck
  - cachetools
  - cattrs
  - certifi
  - cftime
  - charset-normalizer
  - ciso8601
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - colour
  - cycler
  - dask
  - dask-image
  - deepdiff
  - defusedxml
  - distributed
  - docutils
  - fiona
  - Flask
  - Flask-Babel
  - fonttools
  - frozenlist
  - fsspec
  - GeoAlchemy2
  - greenlet
  - HeapDict
  - idna
  - imageio
  - importlib-metadata
  - importlib-resources
  - iso8601
  - itsdangerous
  - Jinja2
  - jmespath
  - jsonschema
  - kiwisolver
  - lark-parser
  - locket
  - lxml
  - MarkupSafe
  - matplotlib-base
  - morecantile
  - multidict
  - munch
  - netCDF4
  - networkx
  - numexpr
  - numpy
  - ordered-set
  - packaging
  - pandas
  - partd
  - Pillow
  - PIMS
  - psutil
  - psycopg2
  - pyasn1
  - pydantic
  - pyerfa
  - pyparsing=2.4.7
  - pyproj
  - pyrsistent
  - pystac
  - pystac-client
  - python-dateutil
  - python-rapidjson
  - python-slugify
  - pytz
  - PyWavelets
  - PyYAML
  - regex
  - requests
  - rsa
  - ruamel.yaml
  - ruamel.yaml.clib
  - s3transfer
  - scikit-image
  - scipy
  - sentry-sdk
  - setuptools-scm
  - Shapely>=2.0
  - six
  - slicerator
  - snuggs
  - sortedcontainers
  - SQLAlchemy<2.0
  - structlog
  - tblib
  - text-unidecode
  - tifffile
  - tomli
  - toolz
  - tornado
  - tqdm
  - typing_extensions
  - urllib3
  - urlpath
  - Werkzeug
  - wrapt
  - xarray>=2023.1.0
  - yarl
  - zict
  - zipp
  - zstandard
